language: node_js
node_js:
- '8'
sudo: required
services:
- docker

env:
 global:
    - access_key_id: $accesskey
    - secret_access_key: $secretkey
    - region: $region

jobs:
  include:
    - stage: deploy
      after_deploy:
          echo "done deploying"
      deploy:
          provider: elasticbeanstalk
          access_key_id: $accesskey
          secret_access_key: $secretkey
          region: $region
          app: $ebapp
          env: $ebenv
          bucket_name: elasticbeanstalk-us-east-1-069653090426
          on:
           branch: master
